/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewAndController;

import ConnectDatabase.ConnectToXampp;
import java.awt.Color;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modun.account;

/**
 *
 * @author LAM
 */
public class ViewLogin_1 extends javax.swing.JFrame {
    private List<account> listACC = new  ArrayList<>();
    private ViewAdmin vAdmin;
    private ViewNhanVien vEmployee;
    /**
     * Creates new form ViewLogin
     */
    public ViewLogin_1() {

        initComponents();
        this.setLocationRelativeTo(null);
        formSignin.setVisible(true);
        formSignup.setVisible(false);
        formForget.setVisible(false);
        formNewPass.setVisible(false);
        gmailSignup.setMargin(new Insets(10, 10, 10, 10));
        getDataFromdataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameLogin1 = new javax.swing.JTextField();
        PassLogin1 = new javax.swing.JPasswordField();
        ConfirmPassLogin1 = new javax.swing.JPasswordField();
        btnLogin1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        formLogin = new javax.swing.JPanel();
        formSignup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gmailSignup = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passSignup = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        nameSignup = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        confirmSignup = new javax.swing.JPasswordField();
        messSignUp = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        formForget = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        formNewPass = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        confirmNewPass = new javax.swing.JPasswordField();
        btnCreateNew = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        gmailForget = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nameForget = new javax.swing.JTextField();
        messForget = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        formSignin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameLogin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passLogin = new javax.swing.JPasswordField();
        messLogin = new javax.swing.JLabel();
        btnlogin = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("ĐĂNG NHẬP");

        jLabel6.setText("Tên đăng nhập");

        jLabel7.setText("Mật khẩu");

        jLabel8.setText("Nhập lại mật khẩu");

        btnLogin1.setText("Đăng nhập");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        jButton3.setText("Thoát");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnLogin1)))
                        .addGap(43, 43, 43)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NameLogin1)
                                .addComponent(PassLogin1)
                                .addComponent(ConfirmPassLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NameLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PassLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ConfirmPassLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin1)
                    .addComponent(jButton3))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formLogin.setBackground(new java.awt.Color(102, 102, 255));
        formLogin.setForeground(new java.awt.Color(204, 204, 255));
        formLogin.setPreferredSize(new java.awt.Dimension(1450, 482));

        formSignup.setBackground(new java.awt.Color(102, 255, 204));
        formSignup.setForeground(new java.awt.Color(102, 255, 204));
        formSignup.setPreferredSize(new java.awt.Dimension(350, 470));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("well come");
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gmail");

        gmailSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gmailSignup.setForeground(new java.awt.Color(51, 255, 204));
        gmailSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        gmailSignup.setMargin(new java.awt.Insets(10, 10, 10, 10));
        gmailSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gmailSignupKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter password");

        passSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passSignup.setForeground(new java.awt.Color(51, 255, 204));
        passSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        passSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passSignupKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("user");

        nameSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameSignup.setForeground(new java.awt.Color(51, 255, 204));
        nameSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nameSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameSignupKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("password");

        confirmSignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmSignup.setForeground(new java.awt.Color(51, 255, 204));
        confirmSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        confirmSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmSignupKeyReleased(evt);
            }
        });

        messSignUp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        messSignUp.setForeground(new java.awt.Color(204, 0, 0));

        jLabel21.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("sigin");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 102));
        jLabel22.setText("Quay lại");

        javax.swing.GroupLayout formSignupLayout = new javax.swing.GroupLayout(formSignup);
        formSignup.setLayout(formSignupLayout);
        formSignupLayout.setHorizontalGroup(
            formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                        .addComponent(messSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(155, 155, 155))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formSignupLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22))
                    .addGroup(formSignupLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gmailSignup)
                                .addComponent(nameSignup, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                            .addComponent(passSignup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmSignup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        formSignupLayout.setVerticalGroup(
            formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSignupLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmailSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        formForget.setBackground(new java.awt.Color(102, 255, 204));
        formForget.setPreferredSize(new java.awt.Dimension(350, 470));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("pass word");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 30));

        formNewPass.setBackground(new java.awt.Color(102, 102, 255));
        formNewPass.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("new pass word");

        jLabel17.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("password authentication");

        newPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        newPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPassKeyReleased(evt);
            }
        });

        confirmNewPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmNewPass.setForeground(new java.awt.Color(51, 255, 204));
        confirmNewPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        confirmNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmNewPassKeyReleased(evt);
            }
        });

        btnCreateNew.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateNew.setForeground(new java.awt.Color(102, 255, 204));
        btnCreateNew.setText("create new");
        btnCreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formNewPassLayout = new javax.swing.GroupLayout(formNewPass);
        formNewPass.setLayout(formNewPassLayout);
        formNewPassLayout.setHorizontalGroup(
            formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formNewPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(newPass))
                .addGap(48, 48, 48))
            .addGroup(formNewPassLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnCreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formNewPassLayout.setVerticalGroup(
            formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNewPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formNewPassLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateNew)
                .addGap(37, 37, 37))
        );

        jLabel14.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gmail");

        gmailForget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gmailForget.setForeground(new java.awt.Color(51, 255, 204));
        gmailForget.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        gmailForget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gmailForgetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gmailForgetKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("user");

        nameForget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameForget.setForeground(new java.awt.Color(51, 255, 204));
        nameForget.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nameForget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameForgetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameForgetKeyReleased(evt);
            }
        });

        messForget.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        messForget.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jLabel19.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("creat new password");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 102));
        jLabel20.setText("Quay lai");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout formForgetLayout = new javax.swing.GroupLayout(formForget);
        formForget.setLayout(formForgetLayout);
        formForgetLayout.setHorizontalGroup(
            formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formForgetLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gmailForget, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameForget, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(messForget, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(77, 77, 77))))
        );
        formForgetLayout.setVerticalGroup(
            formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formForgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gmailForget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameForget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messForget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        formSignin.setBackground(new java.awt.Color(102, 255, 204));
        formSignin.setPreferredSize(new java.awt.Dimension(350, 470));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("well come");
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("user");

        nameLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLogin.setForeground(new java.awt.Color(51, 255, 204));
        nameLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameLoginActionPerformed(evt);
            }
        });
        nameLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameLoginKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("pass word");

        passLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passLogin.setForeground(new java.awt.Color(51, 255, 204));
        passLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        passLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passLoginKeyReleased(evt);
            }
        });

        messLogin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        messLogin.setForeground(new java.awt.Color(255, 0, 0));

        btnlogin.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("login");
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 102));
        jLabel18.setText("Quên mật khẩu");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout formSigninLayout = new javax.swing.GroupLayout(formSignin);
        formSignin.setLayout(formSigninLayout);
        formSigninLayout.setHorizontalGroup(
            formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                        .addComponent(btnlogin)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                        .addComponent(messLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(formSigninLayout.createSequentialGroup()
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addGroup(formSigninLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formSigninLayout.createSequentialGroup()
                                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formSigninLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formSigninLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(nameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        formSigninLayout.setVerticalGroup(
            formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSigninLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlogin)
                .addGap(53, 53, 53)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        javax.swing.GroupLayout formLoginLayout = new javax.swing.GroupLayout(formLogin);
        formLogin.setLayout(formLoginLayout);
        formLoginLayout.setHorizontalGroup(
            formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(formSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(formForget, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(788, Short.MAX_VALUE))
        );
        formLoginLayout.setVerticalGroup(
            formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formForget, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(formSignin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addComponent(formSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 1999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    Lấy dữ liệu từ database
    private void getDataFromdataBase(){
        listACC = ConnectToXampp.findAllAccount();
        for(account acc : listACC){
            System.out.println(acc.getGmail());
        }
    }
    private void resetFormLogin(){
        nameLogin.setText("");
        passLogin.setText("");
    }
    private void resetFormForget(){
        gmailForget.setText("");
        nameForget.setText("");
        newPass.setText("");
        confirmNewPass.setText("");
    }
//    kiểm tra đăng nhập
    private int checkACCLogin(String name, String pass){
        getDataFromdataBase();
        for(account acc : listACC){
            if(name.equals(acc.getName()) && pass.equals(acc.getPass())){
                if(acc.getId() == 1){
                    return 1;
                }else if(acc.getId() >= 2){
                    return 2;
                }
            }else if(name.equals(acc.getName())&& !pass.equals(acc.getPass())){
                return -1;
            }else if(!name.equals(acc.getName())&& pass.equals(acc.getPass())){
                return -2;
            }
        }
        return 0;
    }
//    kiểm tra đăng ký
    private int checkACCSignup(String gmail, String name, String pass, String confirmPass){
        String GMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean checkGmail = gmail.matches(GMAIL_REGEX);
        if(!gmail.equals("") && checkGmail == true && !name.equals("") && name.length() >= 6 && !pass.equals("") && pass.equals(confirmPass) && pass.length() >= 8){
            return 1;
        }
        return 0;
    }
    
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    private void gmailSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmailSignupKeyReleased
        String GMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean checkGmail = (gmailSignup.getText()).matches(GMAIL_REGEX);
        if(checkGmail == false){
            gmailSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Định dạng gmail chưa đúng!");
        }else{
            gmailSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_gmailSignupKeyReleased

    private void nameSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameSignupKeyReleased
        if((nameSignup.getText()).equals("") || nameSignup.getText().length() < 6){
            nameSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Tên đăng nhập phải từ 6 kí tự!");
        }else{
            nameSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_nameSignupKeyReleased

    private void passSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passSignupKeyReleased
        if(passSignup.getPassword().equals("") || passSignup.getPassword().length < 8){
            passSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Mật khẩu phải từ 8 kí tự!");
        }else{
            passSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_passSignupKeyReleased

    private void confirmSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmSignupKeyReleased
        String passSign = String.valueOf(passSignup.getPassword());
        String confirmSign = String.valueOf(confirmSignup.getPassword());
        if(!confirmSign.equals(passSign) || confirmSign.length() < 8){
            confirmSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Mật khẩu xác thực không đúng!");
        }else{
            confirmSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_confirmSignupKeyReleased

    private void gmailForgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmailForgetKeyReleased
        String GMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean checkGmail = (gmailForget.getText()).matches(GMAIL_REGEX);
        if(checkGmail == false){
            gmailForget.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Định dạng gmail chưa đúng!");
        }else{
            gmailForget.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_gmailForgetKeyReleased

    private void nameForgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameForgetKeyReleased
        if((nameForget.getText()).equals("") || nameForget.getText().length() < 6){
            nameForget.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Tên đăng nhập phải từ 6 kí tự!");
        }else{
            nameForget.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_nameForgetKeyReleased

    private void gmailForgetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmailForgetKeyPressed
        newPass.setText("");
        confirmNewPass.setText("");
        formNewPass.setVisible(false);
    }//GEN-LAST:event_gmailForgetKeyPressed

    private void nameForgetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameForgetKeyPressed
        newPass.setText("");
        confirmNewPass.setText("");
        formNewPass.setVisible(false);
    }//GEN-LAST:event_nameForgetKeyPressed

    private void newPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassKeyReleased
        if(newPass.getPassword().equals("") || newPass.getPassword().length < 8){
            newPass.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Mật khẩu phải từ 8 kí tự!");
        }else{
            newPass.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_newPassKeyReleased

    private void confirmNewPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmNewPassKeyReleased
        String newPassF = String.valueOf(newPass.getPassword());
        String newconfirmF = String.valueOf(confirmNewPass.getPassword());
        if(!newPassF.equals(newconfirmF) || newconfirmF.length() < 8){
            confirmNewPass.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Mật khẩu xác thực không đúng!");
        }else{
            confirmNewPass.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_confirmNewPassKeyReleased

    private void btnCreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewActionPerformed
        String newPassF = String.valueOf(newPass.getPassword());
        String newconfirmF = String.valueOf(confirmNewPass.getPassword());
        if(!newPassF.equals("") && newPassF.length() >= 8 && newconfirmF.equals(newPassF)){
            for(account acc : listACC){
                if(acc.getGmail().equals(gmailForget.getText()) && acc.getName().equals(nameForget.getText())){
                    account newAcc = new account(acc.getId(), acc.getGmail(), acc.getName(), newPassF);
                    System.out.println(newAcc.getGmail() + newAcc.getName() + newAcc.getPass() +" "+newAcc.getId()+"");
                    ConnectToXampp.updatePassOfAccount(newAcc);
                    resetFormForget();
                    JOptionPane.showMessageDialog(rootPane, "Tạo mật khẩu thành công: " + newPassF);
                    formForget.setVisible(false);
                    formSignin.setVisible(true);
                    nameLogin.setText(acc.getName());
                    passLogin.setText(newPassF);
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnCreateNewActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
         for(account acc : listACC){
            if(gmailForget.getText().equals(acc.getGmail()) && nameForget.getText().equals(acc.getName())){
                formNewPass.setVisible(true);
                return;
            }else{
                formNewPass.setVisible(false);
                messForget.setText("Thông tin tài khoản không tồn tại!");
            }
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
          formSignin.setVisible(true);
        formSignup.setVisible(false);
        formForget.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        resetFormLogin();
        formSignin.setVisible(false);
        formSignup.setVisible(false);
        formForget.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        String nameLog = nameLogin.getText();
        String passLog = String.copyValueOf(passLogin.getPassword());
        if(nameLog.equals("") || passLog.equals("")){
            messLogin.setText("Vui lòng nhập đầy đủ thông tin!");
            return;
        }else if(nameLog.length() < 6 || passLog.length() < 8){
            messLogin.setText("Vui lòng kiểm tra lại thông tin!");
            return;
        }
        if(checkACCLogin(nameLog, passLog) == 1){
            messLogin.setText("");
            if(vAdmin == null){
                resetFormLogin();
                vAdmin = new ViewAdmin();
            }
            vAdmin.setVisible(true);
        }else if(checkACCLogin(nameLog, passLog) == 2){
            if(vEmployee == null){
                resetFormLogin();
                vEmployee = new ViewNhanVien();
            }
            vEmployee.setVisible(true);
        }else if(checkACCLogin(nameLog, passLog) == -1){
            messLogin.setText("Mật khẩu không đúng!");
        }else if(checkACCLogin(nameLog, passLog) == -2){
            messLogin.setText("Tên đăng nhập không tồn tại!");
        }else if(checkACCLogin(nameLog, passLog) == 0){
            messLogin.setText("Tài khoản không tồn tại!");
        }
    }//GEN-LAST:event_btnloginMouseClicked

    private void passLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passLoginKeyReleased
        if(passLogin.getPassword().equals("") || passLogin.getPassword().length < 8){
            passLogin.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messLogin.setText("Mật khẩu phải từ 8 kí tự!");
        }else{
            passLogin.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messLogin.setText("");
        }
    }//GEN-LAST:event_passLoginKeyReleased

    private void nameLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameLoginKeyReleased
        if((nameLogin.getText()).equals("") || nameLogin.getText().length() < 6){
            nameLogin.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messLogin.setText("Tên đăng nhập phải từ 6 kí tự!");
        }else{
            nameLogin.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messLogin.setText("");
        }
    }//GEN-LAST:event_nameLoginKeyReleased

    private void nameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLoginActionPerformed

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
     String gmailSign = gmailSignup.getText();
        String nameSign = nameSignup.getText();
        String passSign = String.valueOf(passSignup.getPassword());
        String confirmSign = String.valueOf(confirmSignup.getPassword());
        if(gmailSignup.getText().equals("") || nameSignup.getText().equals("") || passSignup.getPassword().equals("") || confirmSignup.getPassword().equals("")){
            messSignUp.setText("Vui lòng điền đầy đủ thông tin!");
            return;
        }
        if(checkACCSignup(gmailSign, nameSign, passSign, confirmSign) == 1){
            JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công tài khoản");
        }else{
            messSignUp.setText("Vui lòng kiểm tra lại thông tin!");
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewLogin_1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassLogin1;
    private javax.swing.JTextField NameLogin1;
    private javax.swing.JPasswordField PassLogin1;
    private javax.swing.JButton btnCreateNew;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel btnlogin;
    private javax.swing.JPasswordField confirmNewPass;
    private javax.swing.JPasswordField confirmSignup;
    private javax.swing.JPanel formForget;
    private javax.swing.JPanel formLogin;
    private javax.swing.JPanel formNewPass;
    private javax.swing.JPanel formSignin;
    private javax.swing.JPanel formSignup;
    private javax.swing.JTextField gmailForget;
    private javax.swing.JTextField gmailSignup;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messForget;
    private javax.swing.JLabel messLogin;
    private javax.swing.JLabel messSignUp;
    private javax.swing.JTextField nameForget;
    private javax.swing.JTextField nameLogin;
    private javax.swing.JTextField nameSignup;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JPasswordField passSignup;
    // End of variables declaration//GEN-END:variables
}
