
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewAndController;

import ConnectDatabase.ConnectToXampp;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modun.banyanFlower;
import modun.listFlower;
import modun.singleFlower;

/**
 *
 * @author LAM
 */
public class ViewAdmin extends javax.swing.JFrame {
    
    private ViewLogin_1 vLogin;
    private List<listFlower> list = new ArrayList<>();
    private List<listFlower> listImport = new ArrayList<>();
    private List<listFlower> listExport = new ArrayList<>();
    private String typeFlowerFormRemove = "";
    private String typeFlowerFormEdit = "";
    /**
     * Creates new form ViewAdmin
     */
    public ViewAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        formHome.setVisible(true);
        formEdit.setVisible(false);
        formDelete.setVisible(false);
        formCinHistory.setVisible(false);
        formCoutHistory.setVisible(false);
        getDataFromDataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnHome = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnHistoryExp = new javax.swing.JLabel();
        btnHistoryImp = new javax.swing.JLabel();
        btnRemove = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLogout1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        formHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHome = new javax.swing.JTable();
        btnExcelHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        formEdit = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEdit = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EditCode = new javax.swing.JTextField();
        EditName = new javax.swing.JTextField();
        EditColor = new javax.swing.JTextField();
        EditSubflower = new javax.swing.JTextField();
        EditPetalsFlower = new javax.swing.JTextField();
        EditAmount = new javax.swing.JTextField();
        EditSingle = new javax.swing.JRadioButton();
        EditBanyan = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        EditCinCode = new javax.swing.JTextField();
        editFindBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        editSave = new javax.swing.JButton();
        editReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        formDelete = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRemove = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        DeleteCode = new javax.swing.JTextField();
        DeleteName = new javax.swing.JTextField();
        DeleteColor = new javax.swing.JTextField();
        DeleteSubflower = new javax.swing.JTextField();
        DeletePetalsFlower = new javax.swing.JTextField();
        DeleteAmount = new javax.swing.JTextField();
        DeleteSingle = new javax.swing.JRadioButton();
        DeleteBanyan = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        DeleteCinCode = new javax.swing.JTextField();
        deleteFindBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        deleteReset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        formCoutHistory = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableExport = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnExcelHome1 = new javax.swing.JButton();
        formCinHistory = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableImport = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        btnExcelHome2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(1400, 800));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-house-64.png"))); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnHistoryExp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistoryExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-book-reading-100.png"))); // NOI18N
        btnHistoryExp.setText("Lịch sử xuất");
        btnHistoryExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryExpMouseClicked(evt);
            }
        });

        btnHistoryImp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistoryImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-book-reading-100.png"))); // NOI18N
        btnHistoryImp.setText(" Lịch sử nhập");
        btnHistoryImp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryImpMouseClicked(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-delete-key-64.png"))); // NOI18N
        btnRemove.setText("Xóa sản phẩm");
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-mechanical-fix-100.png"))); // NOI18N
        btnEdit.setText("Chỉnh sửa sản phẩm");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        btnLogout1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-user-shield-50.png"))); // NOI18N
        btnLogout1.setText("Tạo tài khoản");
        btnLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogout1MouseClicked(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-logout-rounded-50.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistoryImp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistoryExp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistoryImp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistoryExp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewAndController/img/icons8-java-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        formHome.setBackground(new java.awt.Color(102, 102, 255));
        formHome.setForeground(new java.awt.Color(102, 102, 255));

        tableHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu hoa", "Số hoa con", "Số cánh hoa", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tableHome);
        if (tableHome.getColumnModel().getColumnCount() > 0) {
            tableHome.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableHome.getColumnModel().getColumn(1).setMinWidth(100);
            tableHome.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableHome.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableHome.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableHome.getColumnModel().getColumn(5).setPreferredWidth(60);
            tableHome.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        btnExcelHome.setBackground(new java.awt.Color(204, 204, 255));
        btnExcelHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcelHome.setText("Xuất file Excel");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DANH SÁCH HOA TRONG KHO");

        javax.swing.GroupLayout formHomeLayout = new javax.swing.GroupLayout(formHome);
        formHome.setLayout(formHomeLayout);
        formHomeLayout.setHorizontalGroup(
            formHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formHomeLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(formHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExcelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        formHomeLayout.setVerticalGroup(
            formHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formHomeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcelHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formEdit.setBackground(new java.awt.Color(102, 102, 255));

        tableEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu hoa", "Số hoa con", "Số cánh hoa", "Số lượng"
            }
        ));
        tableEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEditMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableEdit);
        if (tableEdit.getColumnModel().getColumnCount() > 0) {
            tableEdit.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableEdit.getColumnModel().getColumn(1).setMinWidth(100);
            tableEdit.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableEdit.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableEdit.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableEdit.getColumnModel().getColumn(5).setPreferredWidth(60);
            tableEdit.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(359, 502));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã hoa");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên hoa");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Loại hoa");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Màu hoa");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Số hoa con");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số cánh hoa");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Số lượng");

        EditName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditNameKeyReleased(evt);
            }
        });

        EditColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditColorKeyReleased(evt);
            }
        });

        EditSubflower.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditSubflowerKeyReleased(evt);
            }
        });

        EditPetalsFlower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPetalsFlowerActionPerformed(evt);
            }
        });
        EditPetalsFlower.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditPetalsFlowerKeyReleased(evt);
            }
        });

        EditAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditAmountKeyReleased(evt);
            }
        });

        editButtonGroup.add(EditSingle);
        EditSingle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditSingle.setText("Hoa đơn");
        EditSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSingleActionPerformed(evt);
            }
        });

        editButtonGroup.add(EditBanyan);
        EditBanyan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditBanyan.setText("Hoa đa");
        EditBanyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBanyanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nhập mã hoa");

        editFindBtn.setText("Tìm");
        editFindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFindBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel13.setText("Chỉnh sửa");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(EditPetalsFlower, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EditColor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EditSubflower, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(EditSingle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditBanyan)))
                            .addComponent(EditName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditCode, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(EditCinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditBanyan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EditSingle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubflower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditPetalsFlower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        editSave.setText("Lưu");
        editSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveActionPerformed(evt);
            }
        });

        editReset.setText("Hủy bỏ");
        editReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editResetActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GIAO DIỆN SỬA");

        javax.swing.GroupLayout formEditLayout = new javax.swing.GroupLayout(formEdit);
        formEdit.setLayout(formEditLayout);
        formEditLayout.setHorizontalGroup(
            formEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditLayout.createSequentialGroup()
                .addGroup(formEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formEditLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(editSave)
                        .addGap(60, 60, 60)
                        .addComponent(editReset))
                    .addGroup(formEditLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(formEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formEditLayout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        formEditLayout.setVerticalGroup(
            formEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editReset)
                    .addComponent(editSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formDelete.setBackground(new java.awt.Color(102, 102, 255));

        tableRemove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu hoa", "Số hoa con", "Số cánh hoa", "Số lượng"
            }
        ));
        tableRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRemoveMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableRemove);
        if (tableRemove.getColumnModel().getColumnCount() > 0) {
            tableRemove.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableRemove.getColumnModel().getColumn(1).setMinWidth(100);
            tableRemove.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableRemove.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableRemove.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableRemove.getColumnModel().getColumn(5).setPreferredWidth(60);
            tableRemove.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(359, 502));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Mã hoa");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tên hoa");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Loại hoa");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Màu hoa");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Số hoa con");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Số cánh hoa");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Số lượng");

        DeletePetalsFlower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePetalsFlowerActionPerformed(evt);
            }
        });

        buttonGroup1.add(DeleteSingle);
        DeleteSingle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteSingle.setText("Hoa đơn");
        DeleteSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSingleActionPerformed(evt);
            }
        });

        buttonGroup1.add(DeleteBanyan);
        DeleteBanyan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteBanyan.setText("Hoa đa");
        DeleteBanyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBanyanActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Nhập mã hoa");

        deleteFindBtn.setText("Tìm");
        deleteFindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFindBtnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel23.setText("Thông tin");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(DeletePetalsFlower, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DeleteColor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DeleteSubflower, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(DeleteSingle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DeleteBanyan)))
                            .addComponent(DeleteName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteCode, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(DeleteCinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DeleteAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteCinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteBanyan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteSingle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteSubflower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeletePetalsFlower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        DeleteBtn.setText("Xóa");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        deleteReset.setText("Hủy bỏ");
        deleteReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResetActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("GIAO DIỆN XÓA");

        javax.swing.GroupLayout formDeleteLayout = new javax.swing.GroupLayout(formDelete);
        formDelete.setLayout(formDeleteLayout);
        formDeleteLayout.setHorizontalGroup(
            formDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDeleteLayout.createSequentialGroup()
                .addGroup(formDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formDeleteLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(DeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteReset)
                        .addGap(47, 47, 47))
                    .addGroup(formDeleteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(formDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        formDeleteLayout.setVerticalGroup(
            formDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDeleteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteReset)
                    .addComponent(DeleteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formCoutHistory.setBackground(new java.awt.Color(102, 102, 255));

        tableExport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu hoa", "Số hoa con", "Số cánh hoa", "Số lượng", "Thời gian xuất"
            }
        ));
        jScrollPane5.setViewportView(tableExport);
        if (tableExport.getColumnModel().getColumnCount() > 0) {
            tableExport.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableExport.getColumnModel().getColumn(1).setMinWidth(100);
            tableExport.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableExport.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableExport.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableExport.getColumnModel().getColumn(5).setPreferredWidth(60);
            tableExport.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DANH SÁCH HOA ĐÃ XUẤT");

        btnExcelHome1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnExcelHome1.setText("Xuất file Excel");

        javax.swing.GroupLayout formCoutHistoryLayout = new javax.swing.GroupLayout(formCoutHistory);
        formCoutHistory.setLayout(formCoutHistoryLayout);
        formCoutHistoryLayout.setHorizontalGroup(
            formCoutHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCoutHistoryLayout.createSequentialGroup()
                .addContainerGap(1001, Short.MAX_VALUE)
                .addComponent(btnExcelHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(formCoutHistoryLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(formCoutHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formCoutHistoryLayout.setVerticalGroup(
            formCoutHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCoutHistoryLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcelHome1)
                .addContainerGap())
        );

        formCinHistory.setBackground(new java.awt.Color(102, 102, 255));
        formCinHistory.setPreferredSize(new java.awt.Dimension(904, 581));

        tableImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hoa", "Tên hoa", "Loại hoa", "Màu hoa", "Số hoa con", "Số cánh hoa", "Số lượng", "Thời gian nhập"
            }
        ));
        jScrollPane6.setViewportView(tableImport);
        if (tableImport.getColumnModel().getColumnCount() > 0) {
            tableImport.getColumnModel().getColumn(0).setPreferredWidth(60);
            tableImport.getColumnModel().getColumn(1).setMinWidth(100);
            tableImport.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableImport.getColumnModel().getColumn(2).setPreferredWidth(60);
            tableImport.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableImport.getColumnModel().getColumn(5).setPreferredWidth(60);
            tableImport.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("DANH SÁCH HOA ĐÃ NHẬP");

        btnExcelHome2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnExcelHome2.setText("Xuất file Excel");

        javax.swing.GroupLayout formCinHistoryLayout = new javax.swing.GroupLayout(formCinHistory);
        formCinHistory.setLayout(formCinHistoryLayout);
        formCinHistoryLayout.setHorizontalGroup(
            formCinHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCinHistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcelHome2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(formCinHistoryLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(formCinHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        formCinHistoryLayout.setVerticalGroup(
            formCinHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCinHistoryLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcelHome2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(2, 625));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formCinHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formCoutHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formCinHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addComponent(formCoutHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getDataFromDataBase(){
        list = ConnectToXampp.findAll();
        List<singleFlower> listSfl = new ArrayList<>();
        List<banyanFlower> listBfl = new ArrayList<>();
        list = ConnectToXampp.findAll();
        for(listFlower flower : list){
            System.out.println(flower.getsubFlowerNum() + " " + flower.getpetalsFlowerNum());
            if(flower.getType().equals("Hoa đơn")){
                listSfl.add(new singleFlower(flower.getpetalsFlowerNum(), flower.getName(), flower.getCode(), flower.getType(), flower.getAmount(), flower.getColor()));
            }
            else if(flower.getType().equals("Hoa đa")){
                listBfl.add(new banyanFlower(flower.getsubFlowerNum(), flower.getName(), flower.getCode(), flower.getType(), flower.getAmount(), flower.getColor()));
            }
        }
        RenderDataOnTable(listSfl, listBfl);
    }
    private void RenderDataOnTable(List<singleFlower> listSfl, List<banyanFlower> listBfl){
        
        Collections.sort(listBfl, (banyanFlower o1, banyanFlower o2) -> o1.getAmount() < o2.getAmount() ? -1 : 1);
        Collections.sort(listSfl, (singleFlower o1, singleFlower o2) -> {
            return o1.getAmount() < o2.getAmount() ? -1 : 1;
        });
        DefaultTableModel table = new DefaultTableModel();
        tableHome.setModel(table);
        tableEdit.setModel(table);
        tableRemove.setModel(table);
        table.addColumn("Mã hoa");
        table.addColumn("Tên hoa");
        table.addColumn("Loại hoa");
        table.addColumn("Màu sắc");
        table.addColumn("Số hoa con");
        table.addColumn("Số cánh hoa");
        table.addColumn("Số lượng");
        for(singleFlower flower : listSfl){
            table.addRow(new Object[] {flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), 0, flower.getPetalsFlowerNum(), flower.getAmount()});
        }
        for(banyanFlower flower : listBfl){
            table.addRow(new Object[] {flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getAmount(), flower.getSubFlowerNum(), 0, flower.getAmount()});
        }
    }
    private void deleteRowTable(){
//        DefaultTableModel tbHome = (DefaultTableModel) tableHome.getModel();
//        DefaultTableModel tbEdit = (DefaultTableModel) tableHome.getModel();
        DefaultTableModel tbRemove = (DefaultTableModel) tableHome.getModel();
        int count = tableHome.getRowCount();
        for(int i = 0; i < count; i++){
//            tbHome.removeRow(count - 1 - i);
//            tbEdit.removeRow(count - 1 - i);
            tbRemove.removeRow(count - 1 - i);
        }
    }
    private void setDataFormRemove(String code, String name, String amount, String color, String type, String subF, String petalsF){
        DeleteCinCode.setText(code);
        DeleteCode.setText(code);
        DeleteName.setText(name);
        if(type.equals("Hoa đơn")){
            DeleteSingle.setSelected(true);
            typeFlowerFormRemove = "Hoa đơn";
        }else if(type.equals("Hoa đa")){
            DeleteBanyan.setSelected(true);
            typeFlowerFormRemove = "Hoa đa";
        }
        DeleteAmount.setText(amount);
        DeleteColor.setText(color);
        DeleteSubflower.setText(subF);
        DeletePetalsFlower.setText(petalsF);
    }
    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        vLogin = new ViewLogin_1();
        this.setVisible(false);
        vLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        formHome.setVisible(true);
        formEdit.setVisible(false);
        formDelete.setVisible(false);
        formCinHistory.setVisible(false);
        formCoutHistory.setVisible(false);
        getDataFromDataBase();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHistoryExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryExpMouseClicked
        // TODO add your handling code here:
        formHome.setVisible(false);
        formEdit.setVisible(false);
        formDelete.setVisible(false);
        formCinHistory.setVisible(false);
        formCoutHistory.setVisible(true);
        getDataExport();
    }//GEN-LAST:event_btnHistoryExpMouseClicked

    private void btnHistoryImpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryImpMouseClicked
        formHome.setVisible(false);
        formEdit.setVisible(false);
        formDelete.setVisible(false);
        formCinHistory.setVisible(true);
        formCoutHistory.setVisible(false);
        getDataImport();
    }//GEN-LAST:event_btnHistoryImpMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        // TODO add your handling code here:
        formHome.setVisible(false);
        formEdit.setVisible(false);
        formDelete.setVisible(true);
        formCinHistory.setVisible(false);
        formCoutHistory.setVisible(false);
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        formHome.setVisible(false);
        formEdit.setVisible(true);
        formDelete.setVisible(false);
        formCinHistory.setVisible(false);
        formCoutHistory.setVisible(false);
    }//GEN-LAST:event_btnEditMouseClicked

    private int checkCinInput(){
        if(EditCinCode.getText().equals("") || EditCode.getText().equals("") || EditName.getText().equals("") || EditColor.getText().equals("")
           || EditAmount.getText().equals("") || EditSubflower.getText().equals("") || EditPetalsFlower.getText().equals("") || typeFlowerFormEdit.equals("")){
             return 1;
        }else{
            for(listFlower flower : list){
                if(EditCinCode.getText().equals(flower.getCode()) && EditCinCode.getText().equals(EditCode.getText())){
                    listFlower FL = new listFlower(EditName.getText(), EditCode.getText(), typeFlowerFormEdit, EditColor.getText(), Integer.parseInt(EditAmount.getText()), Integer.parseInt(EditPetalsFlower.getText()), Integer.parseInt(EditSubflower.getText()), flower.getDay(), flower.getMonth(), flower.getYear());
                    ConnectToXampp.update(FL);
                    getDataFromDataBase();
                    return 2;
                }
            }
        }
        return 0;
    }
    private void editSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveActionPerformed
         if(checkCinInput() == 1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ thông tin!");
         }else if(checkCinInput() == 2){
            JOptionPane.showMessageDialog(rootPane, "Chỉnh sửa thông tin thành công");
         }else{
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy mã đã nhập");
         }
    }//GEN-LAST:event_editSaveActionPerformed

    private void EditSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSingleActionPerformed
        EditSingle.setSelected(true);
        typeFlowerFormEdit = "Hoa đơn";
        System.out.println(typeFlowerFormEdit);
    }//GEN-LAST:event_EditSingleActionPerformed

    private void EditBanyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBanyanActionPerformed
        EditBanyan.setSelected(true);
        typeFlowerFormEdit = "Hoa đa";
        System.out.println(typeFlowerFormEdit);
    }//GEN-LAST:event_EditBanyanActionPerformed

    private void editFindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFindBtnActionPerformed
        for(listFlower flower : list){
            if(EditCinCode.getText().equals(flower.getCode())){
                EditCode.setText(flower.getCode());
                EditName.setText(flower.getName());
                typeFlowerFormEdit = flower.getType();
                if(typeFlowerFormEdit.equals("Hoa đơn")){
                    EditSingle.setSelected(true);
                }else if(typeFlowerFormEdit.equals("Hoa đa")){
                    EditBanyan.setSelected(true);
                }
                EditColor.setText(flower.getColor());
                EditAmount.setText(String.valueOf(flower.getAmount()));
                EditSubflower.setText(String.valueOf(flower.getsubFlowerNum()));
                EditPetalsFlower.setText(String.valueOf(flower.getpetalsFlowerNum()));
                return;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Mã không tồn tại");
    }//GEN-LAST:event_editFindBtnActionPerformed

    private void EditPetalsFlowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPetalsFlowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPetalsFlowerActionPerformed

    private void deleteFindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFindBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFindBtnActionPerformed

    private void DeleteBanyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBanyanActionPerformed
        DeleteBanyan.setSelected(true);
        typeFlowerFormRemove = "Hoa đa";
    }//GEN-LAST:event_DeleteBanyanActionPerformed

    private void DeleteSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSingleActionPerformed
        DeleteSingle.setSelected(true);
        typeFlowerFormRemove = "Hoa đơn";
    }//GEN-LAST:event_DeleteSingleActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int selectedIndex = tableRemove.getSelectedRow();
        if(selectedIndex >= 0){
//            listFlower flower = list.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa dòng đã chọn!");
            if(option == 0){
                ConnectToXampp.delete(DeleteCinCode.getText());
            }
        }else if(!DeleteCinCode.getText().equals("")){
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa dòng đã chọn!");
            if(option == 0){
                ConnectToXampp.delete(DeleteCinCode.getText());
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã hoa hoặc chọn dòng muốn xóa!");
        }
        deleteRowTable();
        getDataFromDataBase();
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void DeletePetalsFlowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePetalsFlowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletePetalsFlowerActionPerformed

    private void btnLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1MouseClicked

    private void tableRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRemoveMouseClicked
        int selectRow = tableRemove.getSelectedRow();
        if(selectRow >= 0){
            String code = (String) tableRemove.getValueAt(selectRow, 0);
            String name = (String) tableRemove.getValueAt(selectRow, 1);
            String type = (String) tableRemove.getValueAt(selectRow, 2);
            typeFlowerFormRemove = type;
            String color = (String) tableRemove.getValueAt(selectRow, 3);
            String amount =  (String) (tableRemove.getValueAt(selectRow, 4)+"");
            String subFlower = (String) (tableRemove.getValueAt(selectRow, 5)+"");
            String petalsFlower = (String) (tableRemove.getValueAt(selectRow, 6)+"");
            setDataFormRemove(code, name, amount, color, type, subFlower, petalsFlower);
        }
    }//GEN-LAST:event_tableRemoveMouseClicked

    private void tableEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEditMouseClicked
        int selectRow = tableEdit.getSelectedRow();
        if(selectRow >= 0){
            String code = (String) tableEdit.getValueAt(selectRow, 0);
            String name = (String) tableEdit.getValueAt(selectRow, 1);
            String type = (String) tableEdit.getValueAt(selectRow, 2);
            typeFlowerFormEdit = type;
            String color = (String) tableEdit.getValueAt(selectRow, 3);
            String amount =  (String) (tableEdit.getValueAt(selectRow, 6)+"");
            String subFlower = (String) (tableEdit.getValueAt(selectRow, 4)+"");
            String petalsFlower = (String) (tableEdit.getValueAt(selectRow, 5)+"");
            EditCinCode.setText(code);
            EditCode.setText(code);
            EditName.setText(name);
            if(typeFlowerFormEdit.equals("Hoa đơn")){
                EditSingle.setSelected(true);
            }else if(typeFlowerFormEdit.equals("Hpa đa")){
                EditBanyan.setSelected(true);
            }
            EditColor.setText(color);
            EditAmount.setText(amount);
            EditSubflower.setText(subFlower);
            EditPetalsFlower.setText(petalsFlower);
        }
    }//GEN-LAST:event_tableEditMouseClicked

    private void editResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editResetActionPerformed
        EditCinCode.setText("");
        EditCode.setText("");
        EditName.setText("");
        editButtonGroup.clearSelection();
        typeFlowerFormEdit = "";
        EditColor.setText("");
        EditAmount.setText("");
        EditSubflower.setText("");
        EditPetalsFlower.setText("");
    }//GEN-LAST:event_editResetActionPerformed

    private void deleteResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResetActionPerformed
        DeleteCinCode.setText("");
        DeleteCode.setText("");
        DeleteName.setText("");
        buttonGroup1.clearSelection();
        typeFlowerFormRemove = "";
        DeleteAmount.setText("");
        DeleteColor.setText("");
        DeleteSubflower.setText("");
        DeletePetalsFlower.setText("");
    }//GEN-LAST:event_deleteResetActionPerformed

    private void EditNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditNameKeyReleased
        String regex = "[0-9]+";
        if(!EditName.getText().matches(regex) && !EditName.getText().equals("")){
            EditName.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
//            messFormCin.setText("");
        }else{
            EditName.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
//            messFormCin.setText("Tên hoa không thể chứa kí tự số");
        }
    }//GEN-LAST:event_EditNameKeyReleased

    private void EditColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditColorKeyReleased
        String regex = "[0-9]+";
        if(!EditColor.getText().matches(regex) && !EditColor.getText().equals("")){
            EditColor.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
//            messFormCin.setText("");
        }else{
            EditColor.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
//            messFormCin.setText("Tên hoa không thể chứa kí tự số");
        }
    }//GEN-LAST:event_EditColorKeyReleased

    private void EditSubflowerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditSubflowerKeyReleased
        String regex = "[0-9]+";
        if(!EditSubflower.getText().matches(regex) && !EditSubflower.getText().equals("")){
            EditSubflower.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
//            messFormCin.setText("Số cánh hoa phải là số nguyên dương");
        }else{
            EditSubflower.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
//            messFormCin.setText("");
        }
    }//GEN-LAST:event_EditSubflowerKeyReleased

    private void EditPetalsFlowerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditPetalsFlowerKeyReleased
        String regex = "[0-9]+";
        if(!EditPetalsFlower.getText().matches(regex) && !EditPetalsFlower.getText().equals("")){
            EditPetalsFlower.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
//            messFormCin.setText("Số cánh hoa phải là số nguyên dương");
        }else{
            EditPetalsFlower.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
//            messFormCin.setText("");
        }
    }//GEN-LAST:event_EditPetalsFlowerKeyReleased

    private void EditAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditAmountKeyReleased
        String regex = "[0-9]+";
        if(!EditAmount.getText().matches(regex) && !EditAmount.getText().equals("")){
            EditAmount.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
//            messFormCin.setText("Số cánh hoa phải là số nguyên dương");
        }else{
            EditAmount.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
//            messFormCin.setText("");
        }
    }//GEN-LAST:event_EditAmountKeyReleased

    private void getDataImport(){
        listImport = ConnectToXampp.findAllImport();
        RenderDataOnTableHistoryImport();
    }
    private void RenderDataOnTableHistoryImport(){
        DefaultTableModel table = new DefaultTableModel();
        tableImport.setModel(table);
        table.addColumn("Mã hoa");
        table.addColumn("Tên hoa");
        table.addColumn("Loại hoa");
        table.addColumn("Màu sắc");
        table.addColumn("Số hoa con");
        table.addColumn("Số cánh hoa");
        table.addColumn("Số lượng");
        table.addColumn("Thời gian nhập");
       
        for (listFlower flower : listImport) {
            String time = flower.getDay()+"/"+flower.getMonth()+"/"+flower.getYear();
            table.addRow(new Object[]{flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getSubFlowerNum(), 0, flower.getAmount(), time});
        }
    }
    private void getDataExport(){
        listExport = ConnectToXampp.findAllExport();
        RenderDataOnTableHistoryExport();
    }
    private void RenderDataOnTableHistoryExport(){
        DefaultTableModel table = new DefaultTableModel();
        tableExport.setModel(table);
        table.addColumn("Mã hoa");
        table.addColumn("Tên hoa");
        table.addColumn("Loại hoa");
        table.addColumn("Màu sắc");
        table.addColumn("Số hoa con");
        table.addColumn("Số cánh hoa");
        table.addColumn("Số lượng");
        table.addColumn("Thời gian nhập");
       
        for (listFlower flower : listExport) {
            String time = flower.getDay()+"/"+flower.getMonth()+"/"+flower.getYear();
            table.addRow(new Object[]{flower.getCode(), flower.getName(), flower.getType(), flower.getColor(), flower.getSubFlowerNum(), 0, flower.getAmount(), time});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeleteAmount;
    private javax.swing.JRadioButton DeleteBanyan;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DeleteCinCode;
    private javax.swing.JTextField DeleteCode;
    private javax.swing.JTextField DeleteColor;
    private javax.swing.JTextField DeleteName;
    private javax.swing.JTextField DeletePetalsFlower;
    private javax.swing.JRadioButton DeleteSingle;
    private javax.swing.JTextField DeleteSubflower;
    private javax.swing.JTextField EditAmount;
    private javax.swing.JRadioButton EditBanyan;
    private javax.swing.JTextField EditCinCode;
    private javax.swing.JTextField EditCode;
    private javax.swing.JTextField EditColor;
    private javax.swing.JTextField EditName;
    private javax.swing.JTextField EditPetalsFlower;
    private javax.swing.JRadioButton EditSingle;
    private javax.swing.JTextField EditSubflower;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JButton btnExcelHome;
    private javax.swing.JButton btnExcelHome1;
    private javax.swing.JButton btnExcelHome2;
    private javax.swing.JLabel btnHistoryExp;
    private javax.swing.JLabel btnHistoryImp;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnLogout1;
    private javax.swing.JLabel btnRemove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteFindBtn;
    private javax.swing.JButton deleteReset;
    private javax.swing.ButtonGroup editButtonGroup;
    private javax.swing.JButton editFindBtn;
    private javax.swing.JButton editReset;
    private javax.swing.JButton editSave;
    private javax.swing.JPanel formCinHistory;
    private javax.swing.JPanel formCoutHistory;
    private javax.swing.JPanel formDelete;
    private javax.swing.JPanel formEdit;
    private javax.swing.JPanel formHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tableEdit;
    private javax.swing.JTable tableExport;
    private javax.swing.JTable tableHome;
    private javax.swing.JTable tableImport;
    private javax.swing.JTable tableRemove;
    // End of variables declaration//GEN-END:variables
}
