/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewAndController;

import ConnectDatabase.ConnectToXampp;
import java.awt.Color;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modun.account;
import viewAndController.ViewAdmin;
import viewAndController.ViewNhanVien;

/**
 *
 * @author LAM
 */
public class ViewLogin extends javax.swing.JFrame {
    private List<account> listACC = new  ArrayList<>();
    private ViewAdmin vAdmin;
    private ViewNhanVien vEmployee;
    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {

        initComponents();
        this.setLocationRelativeTo(null);
        formSignin.setVisible(true);
        formSignup.setVisible(false);
        formForget.setVisible(false);
        formNewPass.setVisible(false);
        gmailSignup.setMargin(new Insets(10, 10, 10, 10));
        getDataFromdataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameLogin1 = new javax.swing.JTextField();
        PassLogin1 = new javax.swing.JPasswordField();
        ConfirmPassLogin1 = new javax.swing.JPasswordField();
        btnLogin1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        formLogin = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        formSignup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gmailSignup = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passSignup = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        nameSignup = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        confirmSignup = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        messSignUp = new javax.swing.JLabel();
        formSignin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameLogin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnForgot = new javax.swing.JButton();
        messLogin = new javax.swing.JLabel();
        formForget = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        formNewPass = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        confirmNewPass = new javax.swing.JPasswordField();
        btnCreateNew = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        gmailForget = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nameForget = new javax.swing.JTextField();
        btnForgetgBack = new javax.swing.JButton();
        btnNewPass = new javax.swing.JButton();
        messForget = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("ĐĂNG NHẬP");

        jLabel6.setText("Tên đăng nhập");

        jLabel7.setText("Mật khẩu");

        jLabel8.setText("Nhập lại mật khẩu");

        btnLogin1.setText("Đăng nhập");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        jButton3.setText("Thoát");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnLogin1)))
                        .addGap(43, 43, 43)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NameLogin1)
                                .addComponent(PassLogin1)
                                .addComponent(ConfirmPassLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NameLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PassLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ConfirmPassLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin1)
                    .addComponent(jButton3))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 494));

        formLogin.setPreferredSize(new java.awt.Dimension(1450, 482));

        left.setPreferredSize(new java.awt.Dimension(175, 0));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        right.setPreferredSize(new java.awt.Dimension(175, 482));

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        formSignup.setPreferredSize(new java.awt.Dimension(350, 470));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ĐĂNG KÝ");
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Gmail");

        gmailSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gmailSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        gmailSignup.setMargin(new java.awt.Insets(10, 10, 10, 10));
        gmailSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gmailSignupKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Xác thực MK");

        passSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        passSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passSignupKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tên đăng nhập");

        nameSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nameSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameSignupKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mật khẩu");

        confirmSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        confirmSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmSignupKeyReleased(evt);
            }
        });

        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignup.setText("Đăng ký");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        messSignUp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        messSignUp.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout formSignupLayout = new javax.swing.GroupLayout(formSignup);
        formSignup.setLayout(formSignupLayout);
        formSignupLayout.setHorizontalGroup(
            formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gmailSignup, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(nameSignup))
                    .addComponent(passSignup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmSignup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addGap(0, 269, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        formSignupLayout.setVerticalGroup(
            formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSignupLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmailSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(messSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(37, 37, 37))
        );

        formSignin.setPreferredSize(new java.awt.Dimension(350, 470));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ĐĂNG NHẬP");
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên đăng nhập");

        nameLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nameLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameLoginKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mật khẩu");

        passLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        passLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passLoginKeyReleased(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnForgot.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnForgot.setText("Quên mật khẩu");
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });

        messLogin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        messLogin.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout formSigninLayout = new javax.swing.GroupLayout(formSignin);
        formSignin.setLayout(formSigninLayout);
        formSigninLayout.setHorizontalGroup(
            formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formSigninLayout.createSequentialGroup()
                        .addComponent(messLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
            .addGroup(formSigninLayout.createSequentialGroup()
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formSigninLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnLogin))
                    .addGroup(formSigninLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnForgot)
                            .addGroup(formSigninLayout.createSequentialGroup()
                                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLogin)
                                    .addComponent(passLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formSigninLayout.setVerticalGroup(
            formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formSigninLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(formSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(messLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnForgot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formForget.setPreferredSize(new java.awt.Dimension(350, 470));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("QUÊN MẬT KHẨU");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Mật khẩu mới");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Xác thực MK");

        newPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        newPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPassKeyReleased(evt);
            }
        });

        confirmNewPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmNewPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        confirmNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmNewPassKeyReleased(evt);
            }
        });

        btnCreateNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateNew.setText("TẠO MỚI");
        btnCreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formNewPassLayout = new javax.swing.GroupLayout(formNewPass);
        formNewPass.setLayout(formNewPassLayout);
        formNewPassLayout.setHorizontalGroup(
            formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formNewPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(formNewPassLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnCreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formNewPassLayout.setVerticalGroup(
            formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNewPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(formNewPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Gmail");

        gmailForget.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gmailForget.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        gmailForget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gmailForgetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gmailForgetKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Tên đăng nhập");

        nameForget.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameForget.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        nameForget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameForgetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameForgetKeyReleased(evt);
            }
        });

        btnForgetgBack.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnForgetgBack.setText("Quay lại");
        btnForgetgBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetgBackActionPerformed(evt);
            }
        });

        btnNewPass.setText("Tạo mật khẩu mới");
        btnNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPassActionPerformed(evt);
            }
        });

        messForget.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        messForget.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout formForgetLayout = new javax.swing.GroupLayout(formForget);
        formForget.setLayout(formForgetLayout);
        formForgetLayout.setHorizontalGroup(
            formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formForgetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameForget)
                    .addComponent(gmailForget))
                .addGap(20, 20, 20))
            .addGroup(formForgetLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formForgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(btnForgetgBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(btnNewPass)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formForgetLayout.createSequentialGroup()
                        .addComponent(messForget, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        formForgetLayout.setVerticalGroup(
            formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formForgetLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmailForget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formForgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameForget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNewPass)
                .addGap(22, 22, 22)
                .addComponent(formNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messForget, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnForgetgBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formLoginLayout = new javax.swing.GroupLayout(formLogin);
        formLogin.setLayout(formLoginLayout);
        formLoginLayout.setHorizontalGroup(
            formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formSignin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formForget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formLoginLayout.setVerticalGroup(
            formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formForget, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(formSignup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(left, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(formSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel18.setText("meomeo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel18)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 1436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(formLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    Lấy dữ liệu từ database
    private void getDataFromdataBase(){
        listACC = ConnectToXampp.findAllAccount();
        for(account acc : listACC){
            System.out.println(acc.getGmail());
        }
    }
    private void resetFormLogin(){
        nameLogin.setText("");
        passLogin.setText("");
    }
    private void resetFormForget(){
        gmailForget.setText("");
        nameForget.setText("");
        newPass.setText("");
        confirmNewPass.setText("");
    }
//    kiểm tra đăng nhập
    private int checkACCLogin(String name, String pass){
        getDataFromdataBase();
        for(account acc : listACC){
            if(name.equals(acc.getName()) && pass.equals(acc.getPass())){
                if(acc.getId() == 1){
                    return 1;
                }else if(acc.getId() >= 2){
                    return 2;
                }
            }else if(name.equals(acc.getName())&& !pass.equals(acc.getPass())){
                return -1;
            }else if(!name.equals(acc.getName())&& pass.equals(acc.getPass())){
                return -2;
            }
        }
        return 0;
    }
//    kiểm tra đăng ký
    private int checkACCSignup(String gmail, String name, String pass, String confirmPass){
        String GMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean checkGmail = gmail.matches(GMAIL_REGEX);
        if(!gmail.equals("") && checkGmail == true && !name.equals("") && name.length() >= 6 && !pass.equals("") && pass.equals(confirmPass) && pass.length() >= 8){
            return 1;
        }
        return 0;
    }
    
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String nameLog = nameLogin.getText();
        String passLog = String.copyValueOf(passLogin.getPassword());
        if(nameLog.equals("") || passLog.equals("")){
            messLogin.setText("Vui lòng nhập đầy đủ thông tin!");
            return;
        }else if(nameLog.length() < 6 || passLog.length() < 8){
            messLogin.setText("Vui lòng kiểm tra lại thông tin!");
            return;
        }
        if(checkACCLogin(nameLog, passLog) == 1){
            messLogin.setText("");
            if(vAdmin == null){
                resetFormLogin();
                vAdmin = new ViewAdmin();
            }
            vAdmin.setVisible(true);
        }else if(checkACCLogin(nameLog, passLog) == 2){
            if(vEmployee == null){
                resetFormLogin();
                vEmployee = new ViewNhanVien();
            }
            vEmployee.setVisible(true);
        }else if(checkACCLogin(nameLog, passLog) == -1){
            messLogin.setText("Mật khẩu không đúng!");
        }else if(checkACCLogin(nameLog, passLog) == -2){
            messLogin.setText("Tên đăng nhập không tồn tại!");
        }else if(checkACCLogin(nameLog, passLog) == 0){
            messLogin.setText("Tài khoản không tồn tại!");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        formSignin.setVisible(true);
        formSignup.setVisible(false);
        formForget.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnForgetgBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetgBackActionPerformed
        formSignin.setVisible(true);
        formSignup.setVisible(false);
        formForget.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnForgetgBackActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        resetFormLogin();
        formSignin.setVisible(false);
        formSignup.setVisible(false);
        formForget.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnForgotActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String gmailSign = gmailSignup.getText();
        String nameSign = nameSignup.getText();
        String passSign = String.valueOf(passSignup.getPassword());
        String confirmSign = String.valueOf(confirmSignup.getPassword());
        if(gmailSignup.getText().equals("") || nameSignup.getText().equals("") || passSignup.getPassword().equals("") || confirmSignup.getPassword().equals("")){
            messSignUp.setText("Vui lòng điền đầy đủ thông tin!");
            return;
        }
        if(checkACCSignup(gmailSign, nameSign, passSign, confirmSign) == 1){
            JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công tài khoản");
        }else{
            messSignUp.setText("Vui lòng kiểm tra lại thông tin!");
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void gmailSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmailSignupKeyReleased
        String GMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean checkGmail = (gmailSignup.getText()).matches(GMAIL_REGEX);
        if(checkGmail == false){
            gmailSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Định dạng gmail chưa đúng!");
        }else{
            gmailSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_gmailSignupKeyReleased

    private void nameSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameSignupKeyReleased
        if((nameSignup.getText()).equals("") || nameSignup.getText().length() < 6){
            nameSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Tên đăng nhập phải từ 6 kí tự!");
        }else{
            nameSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_nameSignupKeyReleased

    private void passSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passSignupKeyReleased
        if(passSignup.getPassword().equals("") || passSignup.getPassword().length < 8){
            passSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Mật khẩu phải từ 8 kí tự!");
        }else{
            passSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_passSignupKeyReleased

    private void confirmSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmSignupKeyReleased
        String passSign = String.valueOf(passSignup.getPassword());
        String confirmSign = String.valueOf(confirmSignup.getPassword());
        if(!confirmSign.equals(passSign) || confirmSign.length() < 8){
            confirmSignup.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messSignUp.setText("Mật khẩu xác thực không đúng!");
        }else{
            confirmSignup.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messSignUp.setText("");
        }
    }//GEN-LAST:event_confirmSignupKeyReleased

    private void btnNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPassActionPerformed
        for(account acc : listACC){
            if(gmailForget.getText().equals(acc.getGmail()) && nameForget.getText().equals(acc.getName())){
                formNewPass.setVisible(true);
                return;
            }else{
                formNewPass.setVisible(false);
                messForget.setText("Thông tin tài khoản không tồn tại!");
            }
        }
    }//GEN-LAST:event_btnNewPassActionPerformed

    private void nameLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameLoginKeyReleased
        if((nameLogin.getText()).equals("") || nameLogin.getText().length() < 6){
            nameLogin.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messLogin.setText("Tên đăng nhập phải từ 6 kí tự!");
        }else{
            nameLogin.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messLogin.setText("");
        }
    }//GEN-LAST:event_nameLoginKeyReleased

    private void passLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passLoginKeyReleased
        if(passLogin.getPassword().equals("") || passLogin.getPassword().length < 8){
            passLogin.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messLogin.setText("Mật khẩu phải từ 8 kí tự!");
        }else{
            passLogin.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messLogin.setText("");
        }
    }//GEN-LAST:event_passLoginKeyReleased

    private void gmailForgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmailForgetKeyReleased
        String GMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        boolean checkGmail = (gmailForget.getText()).matches(GMAIL_REGEX);
        if(checkGmail == false){
            gmailForget.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Định dạng gmail chưa đúng!");
        }else{
            gmailForget.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_gmailForgetKeyReleased

    private void nameForgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameForgetKeyReleased
        if((nameForget.getText()).equals("") || nameForget.getText().length() < 6){
            nameForget.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Tên đăng nhập phải từ 6 kí tự!");
        }else{
            nameForget.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_nameForgetKeyReleased

    private void gmailForgetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmailForgetKeyPressed
        newPass.setText("");
        confirmNewPass.setText("");
        formNewPass.setVisible(false);
    }//GEN-LAST:event_gmailForgetKeyPressed

    private void nameForgetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameForgetKeyPressed
        newPass.setText("");
        confirmNewPass.setText("");
        formNewPass.setVisible(false);
    }//GEN-LAST:event_nameForgetKeyPressed

    private void newPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPassKeyReleased
        if(newPass.getPassword().equals("") || newPass.getPassword().length < 8){
            newPass.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Mật khẩu phải từ 8 kí tự!");
        }else{
            newPass.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_newPassKeyReleased

    private void confirmNewPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmNewPassKeyReleased
        String newPassF = String.valueOf(newPass.getPassword());
        String newconfirmF = String.valueOf(confirmNewPass.getPassword());
        if(!newPassF.equals(newconfirmF) || newconfirmF.length() < 8){
            confirmNewPass.setBorder(BorderFactory.createMatteBorder(1,1,1,1,Color.red));
            messForget.setText("Mật khẩu xác thực không đúng!");
        }else{
            confirmNewPass.setBorder(BorderFactory.createEmptyBorder(1, 10, 1, 1));
            messForget.setText("");
        }
    }//GEN-LAST:event_confirmNewPassKeyReleased

    private void btnCreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewActionPerformed
        String newPassF = String.valueOf(newPass.getPassword());
        String newconfirmF = String.valueOf(confirmNewPass.getPassword());
        if(!newPassF.equals("") && newPassF.length() >= 8 && newconfirmF.equals(newPassF)){
            for(account acc : listACC){
                if(acc.getGmail().equals(gmailForget.getText()) && acc.getName().equals(nameForget.getText())){
                    account newAcc = new account(acc.getId(), acc.getGmail(), acc.getName(), newPassF);
                    System.out.println(newAcc.getGmail() + newAcc.getName() + newAcc.getPass() +" "+newAcc.getId()+"");
                    ConnectToXampp.updatePassOfAccount(newAcc);
                    resetFormForget();
                    JOptionPane.showMessageDialog(rootPane, "Tạo mật khẩu thành công: " + newPassF);
                    formForget.setVisible(false);
                    formSignin.setVisible(true);
                    nameLogin.setText(acc.getName());
                    passLogin.setText(newPassF);
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnCreateNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassLogin1;
    private javax.swing.JTextField NameLogin1;
    private javax.swing.JPasswordField PassLogin1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNew;
    private javax.swing.JButton btnForgetgBack;
    private javax.swing.JButton btnForgot;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnNewPass;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPasswordField confirmNewPass;
    private javax.swing.JPasswordField confirmSignup;
    private javax.swing.JPanel formForget;
    private javax.swing.JPanel formLogin;
    private javax.swing.JPanel formNewPass;
    private javax.swing.JPanel formSignin;
    private javax.swing.JPanel formSignup;
    private javax.swing.JTextField gmailForget;
    private javax.swing.JTextField gmailSignup;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel left;
    private javax.swing.JLabel messForget;
    private javax.swing.JLabel messLogin;
    private javax.swing.JLabel messSignUp;
    private javax.swing.JTextField nameForget;
    private javax.swing.JTextField nameLogin;
    private javax.swing.JTextField nameSignup;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JPasswordField passSignup;
    private javax.swing.JPanel right;
    // End of variables declaration//GEN-END:variables
}
